spring:
  application:
    name: project_tour
    from: no-reply@seoultour.com

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./development
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  servlet:
    jsp:
      init-parameters:
        development: true

logging:
  level:
    root: info
    org:
      springframework:
        security: error
